name: Build APK Otomatis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Ambil Kode Python
      uses: actions/checkout@v3

    - name: Siapkan Sistem Linux dan Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instal Paket Pendukung Android Resmi
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libffi-dev libssl-dev libsqlite3-dev lld

    - name: Kunci Versi Buildozer Stabil
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.36
        pip install buildozer==1.5.0

    - name: Proses Merakit APK Android
      run: |
        buildozer init
        # Setel lisensi dan nama aplikasi
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/title = My Application/title = Kalkulator Abdul/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = kalkulatorabdul/' buildozer.spec
        
        # Selaraskan target python di dalam spesifikasi buildozer
        sed -i 's/#requirements = python3,kivy/requirements = python3==3.11.1,kivy/' buildozer.spec
        sed -i 's/#p4a.branch = master/p4a.branch = release-2024.01.21/' buildozer.spec
        
        # Jalankan kompilasi langsung
        yes | buildozer -v android debug

    - name: Simpan Hasil File APK Matang
      uses: actions/upload-artifact@v4
      with:
        name: APK-Kalkulator-Siap-Pakai
        path: bin/*.apk
