name: Build APK Otomatis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode Python
      uses: actions/checkout@v3

    - name: Siapkan Sistem Linux dan Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instal Kivy dan Buildozer Terbaru
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lld libffi-dev libssl-dev autoconf automake libtool libtool-bin pkg-config zlib1g-dev
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Buat Konfigurasi APK Instan
      run: |
        buildozer init
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/title = My Application/title = Kalkulator Abdul/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = kalkulatorabdul/' buildozer.spec

    - name: Proses Merakit APK Android
      run: |
        yes | buildozer -v android debug

    - name: Simpan Hasil File APK Matang
      uses: actions/upload-artifact@v4
      with:
        name: APK-Kalkulator-Siap-Pakai
        path: bin/*.apk
