name: Build APK Otomatis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Ambil Kode Python
      uses: actions/checkout@v3

    - name: Siapkan Sistem Linux dan Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instal Alat Rakit
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libffi-dev libssl-dev libsqlite3-dev lld
        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer==1.5.0

    - name: Proses Merakit APK Android
      run: |
        buildozer init
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/title = My Application/title = Kalkulator Abdul/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = kalkulatorabdul/' buildozer.spec
        yes | buildozer -v android debug

    - name: Simpan Hasil File APK Matang
      uses: actions/upload-artifact@v4
      with:
        name: APK-Kalkulator-Siap-Pakai
        path: bin/*.apk
